# Generated by Django 3.1 on 2020-08-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs_app', '0002_auto_20200827_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_assigned',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_completed',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
